on:
  push:
    branches: [master]

jobs:
  abell-deploy:
    runs-on: ubuntu-latest
    name: Abell Website Deployment
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Abell Pages Action
      id: abell-pages
      uses: saurabhdaware/abell-pages-action@v0.10.0
      with:
        site-path: 'https://github.com/saurabhdaware/abell-readme-layout'
        deploy-branch: 'master'
